### ISSUE TITLE
Comma-Separated Selectors

### ISSUE THREAD

**Issue by cyouh95** [lrenjones/prj-rev-bwfs-dasmoto#3]
Alternatively, you could use comma-separated selectors to specify shared properties among multiple elements:

```css
h1, h2, .price {
  font-weight: bold;
}
```

https://github.com/lrenjones/prj-rev-bwfs-dasmoto/blob/master/ArtsCrafts/resources/style.css
